package application;

import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;

public class Main extends Application {
	
    //the following code was generated by SceneBuilder
    @Override
    public void start(Stage primaryStage) {
            Parent root;
            try {
                    root = FXMLLoader.load(getClass().getResource("SimpleView.fxml"));
                    Scene scene = new Scene(root);
                    primaryStage.setScene(scene);
                    primaryStage.sizeToScene();
                    primaryStage.show();
                    primaryStage.setTitle("PRO3600_Reversi");
            }
            catch (IOException e) {
                    e.printStackTrace();
                    return;
            }
    }

	
	//global variables in Main class in order to easily communicate with SimpleViewCtrl.java
	private static GameState test;
    static Game testGame;
    
    public static void main(String[] args) {
    	test = new GameState(); //initialize before launch(args) because SceneBuilder waits for events
    	testGame = new Game(test);
    	launch(args); //launches the GUI
    }
}
